spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/example?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.nirvana.example.model.*
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
    - com.nirvana.web.common.mybatis.BaseMapper

pagehelper:
  support-methods-arguments: true